name: Flask
channels:
  - conda-forge
  - defaults
dependencies:
  - blinker=1.6.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - flask=2.3.3
  - idna=3.4
  - importlib-metadata=6.8.0
  - intel-openmp=2023.2.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.43.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - numpy=1.26.0
  - openssl=3.1.3
  - pandas=2.1.1
  - pip=23.2.1
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - tbb=2021.10.0
  - tk=8.6.13
  - tqdm=4.66.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=2.0.5
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - werkzeug=2.3.7
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - zipp=3.17.0